#
#   @file : dependabot.yml
#   @date : 30 September 2022
#   @authors : Orel Adivi and Daniel Noor
#
# Dependabot
name: Dependabot - Security

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
