remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: CorSys - Synthesizing & Correcting
description: Synthesizing best-effort python expressions while weighting the chance for mistakes in given user outputs.
show_downloads: true
