#
#   @file : dependency-review.yml
#   @date : 30 September 2022
#   @authors : Orel Adivi and Daniel Noor
#
# Dependency Review
name: Dependency Review - Security

on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
